### PR TITLE
Fix crash on S8 sampling in example

### PR DESCRIPTION
**Pull request by elisachisari**
Sampling over S8 in cosmic shear example file was broken. This is a quick fix.

### CODE REVIEW

**Comment by marcpaterno** [comment]
Elisa, can you tell us what version of the CosmoSIS Standard Library you are using? This seems to be reverting to an older version of the CSL; we would prefer, if possible, to move everyone to using the newer version.

If we need to support multiple inconsistent versions of CosmoSIS and CSL (and perhaps also NumCosmo, and Cobaya), we'll need to discuss how we should do so. We had the discussion for CCL, where the conclusion was ... don't support the older versions.

**Comment by marcpaterno** [comment]
@joezuntz In the current version of CosmoSIS, is the `sigma8_rescale` module deprecated? If not, if someone both sets `sigma8` and uses the `sigma8_rescale` module, does anything weird happen? It appears that `sigma8_rescale` reads `sigma8_input`, which is already marked as deprecated.

**Comment by tilmantroester** [comment]
As of v2.5 of the CSL (and v3.3.2 of cobaya), sigma8 can be used as an input to CAMB without approximations or notable performance hits, so earlier methods like `sigma8_rescale` or `sigma8toAs` aren't required any more.

**Comment by marcpaterno** [comment]
These changes would revert the example to use a configuration that was required by older versions of CosmoSIS. While it also works with the newer version of CosmoSIS the result is:
1. less efficient, and 
2. does not deal correctly with non-linear power spectra coming from CAMB.

We would prefer to reject this PR (to not revert the configuration) unless there is a need to retain examples supporting the older version of CosmoSIS.

Is there such a need?

**Comment by elisachisari** [comment]
Tried updating the environment to work with latest CSL and the sampling over S8 works out of the box. So I'm happy to close this.

**Pull request closed without merging**
