### PR TITLE
README file formatting correction

### PR DESCRIPTION
**Pull request by am610**
Formatting corrections.

### CODE REVIEW

**Review by marcpaterno — COMMENTED** [review]
Please check that description of the LSST DESC formatted file is correct. For example, are the keywords VARNAMES and ROW actually present in the DESC-formatted file?

**Comment by am610** [comment]
> VARNAMES and ROW actually present

Yes this keywords are present. It is so because the same file will be also used in SNANA fast cosmology fitter code : WFIt. Which makes use of this keywords.

**Comment by am610** [comment]
I am not sure, why the fifth check is getting canceled. Can you please advise what should I do?

**Comment by marcpaterno** [comment]
I am approving this PR even though there is a failing check. The failure does not seem to be related to the content of this PR, which changes only a README file.

**Pull request merged**
