### PR TITLE
Add support for non-linear models

### PR DESCRIPTION
**Pull request by tilmantroester**
This is a draft implementation to address #174 based on discussions with @jablazek, @paulrogozenski, @chrgeorgiou. It currently supports perturbative IA and galaxy bias models but it should be extendable to halo-model-based models. An example (`examples/des_y1_3x2pt/des_y1_3x2pt_PT.py`) showcases this functionality and compares the results to a direct CCL calculation of the same quantities. They seem to match well!

Allowing support for non-linear quantities requires extensive changes to how firecrown handles two-point statistics and passes around cosmology objects. The main changes are

- Add a `CosmologyBundle` class that bundles the `ccl.Cosmology` object with associated data, such as PT calculators. This class gets passed around as `cosmo` instead of the `ccl.Cosmology` object downstream of the top-level `Likelihood` call.
- Add a `TracerBundle` class that bundles a `ccl.Tracer` object with information about the associated 3D field and `ccl.nl_pt.PTTracers`, where relevant.
- Add a `CosmoSystematicsLikelihood` likelihood class that can account for cosmology-level systematics. The concrete example here is the new class `PTSystematic`, which populates the PT workspaces and computes the basic perturbative quantities that are later used in `TwoPoint.compute`
- Changed how `Source.create_tracer` and `TwoPoint.compute` work to deal with the multiple tracers that are now required per `Source`
- Add a `TattAlignmentSystematic` and `PTNonLinearBiasSystematic` systematic that make use of all this new functionality
- Some refactoring in `number_counts.py` to more generally deal with magnification bias

A plot showing the agreement with CCL:
pt_cls
This PR currently uses the `pt_enh` branch of CCL, since it required some extra functionality there.

### CODE REVIEW

**Comment by tilmantroester** [comment]
@marcpaterno, @vitenti Do you have comments or suggestions on the overall structure of the implementation? There's still quite some clean-up to do but I want to make sure you're on board with the design before investing more time in writing and changing the code.

**Comment by vitenti** [comment]
@tilmantroester yesterday Marc and I finished the design and I did most of the implementation this morning, I'll push it so we can discuss if it fits all the needs.

**Comment by vitenti** [comment]
@tilmantroester We are still reviewing the code structure and figuring out how to better integrate with design we were developing for the toolset.

**Comment by marcpaterno** [comment]
@tilmantroester We have just cut firecrown release v1.3.0, containing (among other things) the new version of the likelihood "factory script".

Would you like this code to make it into a v1.4.0, which we could cut in the next week or two? As of our last meeting, our plan was to release this code to be used in the forecasting project (DESC project 291) and to make the generalization/refactoring we discussed as a task to be done after that release.

**Comment by tilmantroester** [comment]
I'm busy until next week but after that I'll try to get this ready to be reviewed.

**Comment by tilmantroester** [comment]
This should now be ready to be looked at again. I've added a unit test which automatises the example scripts. This should now also handle combinations of PT and non-PT tracers, following a similar approach to @paulrogozenski.

One thing to discuss is whether to use the `firecrown.likelihood.Cosmology` everywhere. Right now the methods of `Likelihood` still take `pyccl.Cosmology` arguments, and only for certain downstream cases `Statistic.compute`, the firecrown `Cosmology` class is used.

**Comment by tilmantroester** [comment]
This is now finally passing all tests.

**Review by vitenti — APPROVED** [review]

**Pull request merged**
